# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-04-05 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursefavorite',
            name='course',
        ),
    ]
