# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-04-07 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_viedo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='viedo',
            name='learn_times',
            field=models.IntegerField(default=0, verbose_name='学习时长（分钟数）'),
        ),
    ]
