# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-04-07 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='', max_length=300, verbose_name='老师告诉你能学到什么？'),
        ),
        migrations.AddField(
            model_name='course',
            name='youneed_known',
            field=models.CharField(default='', max_length=300, verbose_name='课程须知'),
        ),
    ]
